In [1]:
import numpy as np
from sklearn import datasets
iris_X, iris_y = datasets.load_iris(return_X_y=True)
np.unique(iris_y)

array([0, 1, 2])

In [2]:
# Split iris data in train and test data
# A random permutation, to split the data randomly

np.random.seed(0)
indices = np.random.permutation(len(iris_X))

# Recall that the [:-1] Python syntax produces a new array that contains all but the last item
print(indices[-10:])
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]


[ 88  70  87  36  21   9 103  67 117  47]


In [12]:
# Create and fit a nearest-neighbor classifier
# Use the ? to find out more about the syntax
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 7)
knn.fit(iris_X_train, iris_y_train)

# Test accuracy
myPredict = knn.predict(iris_X_test)
myScore = knn.score(iris_X_test, iris_y_test)
print(myPredict) # Predicted value
print(iris_y_test) # True value
print(myScore) # My knn model is 90% accurate for the test data set

[1 2 1 0 0 0 2 1 2 0]
[1 1 1 0 0 0 2 1 2 0]
0.9
